apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-lab-config
  namespace: production
  labels:
    app: sre-lab-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "srelab"
  LOG_LEVEL: "info"