apiVersion: v1
kind: Service
metadata:
  name: sre-lab-api
  namespace: production
  labels:
    app: sre-lab-api
spec:
  type: ClusterIP
  selector:
    app: sre-lab-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http